### ISSUE TITLE
How can I retrain text model " sent_en_char.tar.bz2"?

### ISSUE THREAD

**Issue by prateeknepaliya09** [jolibrain/deepdetect#412]
I want to train the last 2 layers of this model with my data, can I do that, If so, how?

**Comment by beniz** [comment]
Hi, you can either:
- use the `finetune` parameter so that DD finetunes the model on your own dataset, see https://deepdetect.com/overview/examples/#finetuning-googlenet:9ecc00cd7c4c5bc9e8febc4fe00186bf and API documentation
- modify the last two layers of the `convnet.prototxt` by hand and train over it.

**Comment by beniz** [comment]
- we can't share the data, even that old
- all information is available here: https://deepdetect.com/applications/text_model/
- data is labeled
- no preprocessing outside the dataset format, see the convolutional character based models from the link above.
