### ISSUE TITLE
Using other libraries within deepdetect

### ISSUE THREAD

**Issue by AminUCo** [jolibrain/deepdetect#440]
- Version of DeepDetect:
    - [x] Docker

Hi ,  I have a code which has used dlib library and i want to use it within deepdetect service , i didnt find any clue to do this . how can i do that ? 
the more general question is how to run a code with other libraries like dlib , opencv ,... within deepdetect service  ?

**Comment by cchadowitz-pf** [comment]
Hi, I'm responsible for the dlib integration with deepdetect so far. Because of the way dlib defines its models/networks, the dlib-deepdetect integration currently only supports two network architectures (check them out here: https://github.com/cchadowitz-pf/deepdetect/blob/d5abc8884b199317813d8d8c43afdbdcbb17c0f0/src/backends/dlib/DNNStructures.h)

These are the same network architectures as dlib's face detection model and front+rear vehicle detection model. See some more details and examples in #425.

Generally speaking, OpenCV is already used within the DeepDetect service for image transformations and reading/writing, etc, but you'll have to be a bit more clear as to what you're looking to do with specific libraries. It's not entirely up to date, but the main README (https://github.com/jolibrain/deepdetect/#machine-learning-functionalities-per-library-current) shows you some details about which libraries are supported with what functionality (I believe it now also includes Caffe2).
