### ISSUE TITLE
Finetuning impossible

### ISSUE THREAD

**Issue by YaYaB** [jolibrain/deepdetect#505]
I have an issue trying to finetune a model.

#### Configuration
- Version of DeepDetect:
    - Locally compiled on Ubuntu 16.04 LTS
- Commit (shown by the server when starting):
    - Branch `Master`, c67f7338c7db276146347d2f3cd3dc1d0c5cd497
- GPUS:
    - 1 x Nvidia GTX Titan X (Maxwell)

#### Your question / the problem you're facing:
I am not able to finetune a model using DeepDetect. I've updated my DD version that was a bit old and now when I try to finetune a model I get the following error

```
[2018-10-10 12:33:32.333] [img] [info] instantiating model template googlenet
[2018-10-10 12:33:32.333] [img] [info] source=../templates/caffe/googlenet/
[2018-10-10 12:33:32.333] [img] [info] dest=/home/repo/googlenet.prototxt
[2018-10-10 12:33:32.339] [img] [error] service creation mllib bad param: finetuning requires specifying an existing weights file
```

However in my request I specify the **weights**. I did an investigation and I tried a build version from older commits and I finally found the commit that broke this feature.
It is the following one f4d27300633b7fa4a3920bc100ecee7dde013890.

I don't understand the purpose of that commit, because it seems to replace the **weights** and **state** argument given in the CURL request even by something that is empty.

**Comment by fantes** [comment]
http://github.com/fantes/deepdetect.git debug_renewal (PR'ed) 
should add correct check

**Comment by beniz** [comment]
@fantes Not sure #506 does the job. The issue as far as I can understand it, is that they may have a model repository with multiple checkpoints in it. They try selecting one for testing or finetuning typically focing it using the  `weights` API parameter. 

__That being said, I do not understand how the finetuning can fail though, since a checkpoint file should be detected whatsover, unless the file specified by `weights` is not within the model directory.__

@fantes in your PR  `weightsf` grabs the most recent checkpoint and overrides any other option.

My initial commit was introduced to allow renewal of the loaded model, typically loading up the last model checkpoint automatically, replacing finetuned weights.

In practice, testing multiple checkpoints is somewhat a corner case since we now have the automated handling of the `best_model.txt` file from which we can get the best model checkpoint in a single lookup. 

However, API-wise, we may want the `weights` value to stick, but this is more involved.

@fantes @YaYaB let me know if I'm missing something.

**Comment by YaYaB** [comment]
@beniz This is not the issue we had.
Basically I wanted to use a pretrained googlenet on Imagenet and finetune the weights for my own data.
However as you can see when I try after the commit https://github.com/jolibrain/deepdetect/commit/c67f7338c7db276146347d2f3cd3dc1d0c5cd497 , it fails.

**Comment by fantes** [comment]
@beniz the problem is occuring when weightfs still is "" after searching for the most recent checkpoint, so when there is no checkpoint. In such case the "" is unconditionality affected to _weights , that was the understanding behind  my very quick fix. But I almost never use finetune, so there are a lot of chances that I missed something either in the API or the order everything is initialized/copyied/adapted for finetuning

**Comment by beniz** [comment]
So I believe @fantes and I understand what you are doing @YaYaB. Are you passing a file path to `weights` ? `weights` needs to find a file that is within the model repository. This is because DD enforces that model repositories are self-contained. 

If you were passing filepaths in the past, you were using a non-feature :) @fantes and I have discussed the capability to have paths, but this would impose having more flags and another slightly modified mechanism.

On our DD platform that sits on top of DD weights are copied to the model repository and models finetuned daily that way.

Let us know whether we got it right this time.

**Comment by YaYaB** [comment]
Yes, this is what I am doing. Damn I loved this non-feature!!
So what should I do if a want to finetune? Copy the weights inside the repository after creation of the repository and train after that?
May be I did not read well but it would be nice to have this explicitly explained on the API documentation.

A solution could be: when we create a repository with a template it would be nice to have a flag indication weights for instance so that it can copy it to the repository and by default copy the default models that you share
