### ISSUE TITLE
[documentation] parameter "scale" for image input connector may be misleading

### ISSUE THREAD

**Issue by BynaryCobweb** [jolibrain/deepdetect#869]
# Documentation

In backend torch, we use the parameter `scale` to scale all the pixel values of the images, however, in documentation `scale` is presented as follow:

Parameter | Type | Optional | Default | Description
-- | -- | -- | -- | --
scale | float | yes | 1.0 | whether to scale the size of an image

Is the behavior in other backends (caffe for example) similar to torch ? If so, I can update the doc

**Comment by fantes** [comment]
scale should be an input parameter not a mllib param

**Comment by beniz** [comment]
`scale` in the generic image input connector does resize the image, here: https://github.com/jolibrain/deepdetect/blob/master/src/imginputfileconn.h#L173

I don't see it used differently in torch, is it ?

**Comment by BynaryCobweb** [comment]
It's used [here](https://github.com/jolibrain/deepdetect/blob/6238dd4698c9ea674852bf895384ec7ed75f0c8b/src/backends/torch/torchinputconns.cc#L637) in the torchinputconnector, and the behavior is the one I described before

**Comment by beniz** [comment]
Image scaling appears to mean resizing: https://en.wikipedia.org/wiki/Image_scaling

Now, it seems confusion is arising from `scale_min` and `scale_max` being used to resize images, and `scale` being used to modify pixels by a constant factor. Maybe fixing the documentation at this stage is enough, and that'd be a good catch.

It actually doesn't make sense to use `scale` as a single factor for image resizing since neural net inputs are fixed. 

Also not that `width` and `height` are the most common options to force the size of an image, so `scale_min` and `scale_max` could possibly be removed ? They do not appear to be actually used by the torch backend.

**Comment by BynaryCobweb** [comment]
I agree to remove `scale_min` and `scale_max` if they are not used, since neural nets generally require fixed input size (to my knowledge) `width` and `height` seem to be sufficient.

So we can keep `scale` for multiplication of pixels values by a constant factor, and remove `scale_min` & `scale_max` if they are not used by dd?

**Comment by BynaryCobweb** [comment]
`_scale_min` and `_scale_max` were added in [this commit](https://github.com/jolibrain/deepdetect/commit/8d3a16525ce1ee56f204b6d27c3b898aa96d5e5a)
